# Generated by Django 2.2.6 on 2019-10-17 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chair',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='chair',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='chair',
            old_name='Summary',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='chair',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Summary',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Title',
            new_name='title',
        ),
    ]
